version: 2.1

parameters:
  min_desconto_usados: # Renomeado para clareza
    type: string
    default: "40" # Seu limite de 40%
  usar_historico_usados: # Renomeado para clareza
    type: boolean
    default: true

jobs:
  executar_scraper_usados: # Nome do job atualizado
    docker:
      - image: cimg/python:3.11-browsers
    environment:
      PYTHONUNBUFFERED: "1"
      MIN_DESCONTO_PERCENTUAL_USADOS: << pipeline.parameters.min_desconto_usados >>
      USAR_HISTORICO_GLOBAL_USADOS: << pipeline.parameters.usar_historico_usados >>
      # Defina seus tokens e IDs de chat como variáveis de ambiente no CircleCI
      # TELEGRAM_TOKEN: "SEU_TOKEN_AQUI"
      # TELEGRAM_CHAT_ID: "SEU_CHAT_ID_AQUI"
    steps:
      - checkout
      - run:
          name: Instalar dependências Python
          command: |
            python -m pip install --upgrade pip
            pip install selenium python-telegram-bot==20.3 webdriver-manager
      - restore_cache:
          name: Restaurar histórico de preços de USADOS
          keys:
            - v1-usados-historico-cache-{{ .Branch }}-
            - v1-usados-historico-cache-
      - run:
          name: Executar Script Orquestrador de Scraping de USADOS
          command: python scripts/orchestrator_usados.py # Novo nome do script
      - run:
          name: Verificar arquivos gerados nos diretórios de output (USADOS)
          command: |
            echo "================================================================"
            echo "VERIFICANDO DIRETÓRIO DE HISTÓRICO (history_files_usados/):"
            ls -la history_files_usados/ || echo "AVISO: Diretório history_files_usados/ não encontrado ou vazio."
            echo "----------------------------------------------------------------"
            echo "VERIFICANDO DIRETÓRIO DE LOGS DE DEBUG (debug_logs_usados/):"
            ls -la debug_logs_usados/ || echo "AVISO: Diretório debug_logs_usados/ não encontrado ou vazio."
            echo "================================================================"
      - save_cache:
          name: Salvar histórico de preços de USADOS
          key: v1-usados-historico-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - "history_files_usados" # Novo diretório de histórico
      - store_artifacts:
          name: Armazenar histórico de preços de USADOS
          path: "history_files_usados"
          destination: history_files_usados
          when: always
      - store_artifacts:
          name: Armazenar logs de debug de USADOS
          path: "debug_logs_usados"
          destination: debug_logs_usados
          when: always

workflows:
  workflow_usados: # Nome do workflow atualizado
    jobs:
      - executar_scraper_usados
