version: 2.1
 
parameters:
  min_desconto_usados:
    type: string
    default: "40"
  usar_historico_usados:
    type: boolean
    default: true

jobs:
  executar_scraper_usados:
    docker:
      - image: cimg/python:3.11-browsers
    environment:
      PYTHONUNBUFFERED: "1"
      MIN_DESCONTO_PERCENTUAL_USADOS: << pipeline.parameters.min_desconto_usados >>
      USAR_HISTORICO_USADOS: << pipeline.parameters.usar_historico_usados >>
    steps:
      - checkout
      - run:
          name: Instalar dependências Python
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            # Verificar se fake-useragent está instalado
            pip show fake-useragent || echo "fake-useragent não encontrado!"
      - restore_cache:
          name: Restaurar histórico
          keys:
            - v1-usados-historico-cache-{{ checksum "requirements.txt" }}
            - v1-usados-historico-cache-
      - run:
          name: Executar Script Orquestrador
          no_output_timeout: 45m
          command: python scripts/orchestrator_usados.py
      - run:
          name: Verificar arquivos gerados
          command: |
            echo "Conteúdo de history_files_usados:"
            ls -la history_files_usados/ || echo "Diretório vazio."
            if [ -f history_files_usados/price_history_USADOS_GERAL.json ]; then
              head -n 20 history_files_usados/price_history_USADOS_GERAL.json
            else
              echo "Arquivo de histórico não encontrado."
            fi
            echo "Conteúdo de debug_logs_usados:"
            ls -la debug_logs_usados/ || echo "Diretório vazio."
            for log in debug_logs_usados/*.log; do
              if [ -f "$log" ]; then
                echo "Últimas 20 linhas de $log:"
                tail -n 20 "$log"
              fi
            done
      - save_cache:
          name: Salvar histórico
          key: v1-usados-historico-cache-{{ checksum "requirements.txt" }}-{{ epoch }}
          paths:
            - "history_files_usados"
      - store_artifacts:
          path: "history_files_usados"
          destination: history_files_usados
          when: always
      - store_artifacts:
          path: "debug_logs_usados"
          destination: debug_logs_usados
          when:
