jobs:
  executar_scraper_usados:
    docker:
      - image: cimg/python:3.11-browsers
    environment:
      PYTHONUNBUFFERED: "1"
      MIN_DESCONTO_PERCENTUAL_USADOS: << pipeline.parameters.min_desconto_usados >>
      USAR_HISTORICO_GLOBAL_USADOS: << pipeline.parameters.usar_historico_usados >>
    steps:
      - checkout
      - run:
          name: Instalar dependências Python
          command: |
            python -m pip install --upgrade pip
            pip install selenium python-telegram-bot==20.3 webdriver-manager
      - restore_cache:
          name: Restaurar histórico de preços de USADOS
          keys:
            - v1-usados-historico-cache-{{ .Branch }}-
            - v1-usados-historico-cache-
      - run:
          name: Executar Script Orquestrador de Scraping de USADOS
          no_output_timeout: 30m  # ✅ Correto aqui!
          command: python scripts/orchestrator_usados.py
      - run:
          name: Verificar arquivos gerados nos diretórios de output (USADOS)
          command: |
            echo "================================================================"
            echo "VERIFICANDO DIRETÓRIO DE HISTÓRICO (history_files_usados/):"
            ls -la history_files_usados/ || echo "AVISO: Diretório history_files_usados/ não encontrado ou vazio."
            echo "----------------------------------------------------------------"
            echo "VERIFICANDO DIRETÓRIO DE LOGS DE DEBUG (debug_logs_usados/):"
            ls -la debug_logs_usados/ || echo "AVISO: Diretório debug_logs_usados/ não encontrado ou vazio."
            echo "================================================================"
      - save_cache:
          name: Salvar histórico de preços de USADOS
          key: v1-usados-historico-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - "history_files_usados"
      - store_artifacts:
          name: Armazenar histórico de preços de USADOS
          path: "history_files_usados"
          destination: history_files_usados
          when: always
      - store_artifacts:
          name: Armazenar logs de debug de USADOS
          path: "debug_logs_usados"
          destination: debug_logs_usados
          when: always
